/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 05 15:25:56 GMT 2024
 */

package org.isf.vaccine.model;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.isf.vaccine.model.Vaccine;
import org.isf.vactype.model.VaccineType;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Vaccine_ESTest extends Vaccine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Vaccine vaccine0 = new Vaccine("9|>RKz>MW.\f;{S", "dicomSeriesUID", (VaccineType) null);
      assertEquals("9|>RKz>MW.\f;{S", vaccine0.getCode());
      assertEquals("dicomSeriesUID", vaccine0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Vaccine vaccine0 = new Vaccine();
      VaccineType vaccineType0 = vaccine0.getVaccineType();
      assertNull(vaccineType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Vaccine vaccine0 = new Vaccine();
      String string0 = vaccine0.print();
      assertEquals("Vaccine code =.null. description =.null.", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Vaccine vaccine0 = new Vaccine();
      vaccine0.setDescription("9*F");
      assertNull(vaccine0.getCode());
  }
}
