/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 05 15:11:48 GMT 2024
 */

package org.isf.vaccine.manager;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.isf.vaccine.manager.VaccineBrowserManager;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VaccineBrowserManager_ESTest extends VaccineBrowserManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VaccineBrowserManager vaccineBrowserManager0 = new VaccineBrowserManager();
      // Undeclared exception!
      try { 
        vaccineBrowserManager0.getVaccine();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.isf.vaccine.manager.VaccineBrowserManager", e);
      }
  }
}
