/*
 * This file was automatically generated by EvoSuite
 * Fri Jul 05 15:30:42 GMT 2024
 */

package org.isf.vaccine.service;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.isf.vaccine.model.Vaccine;
import org.isf.vaccine.service.VaccineIoOperations;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VaccineIoOperations_ESTest extends VaccineIoOperations_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VaccineIoOperations vaccineIoOperations0 = new VaccineIoOperations();
      String string0 = "ZA+QC}\\uH|3`(k";
      // Undeclared exception!
      try { 
        vaccineIoOperations0.findVaccine(string0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/isf/vaccine/service/VaccineIoOperationRepository
         //
         verifyException("org.isf.vaccine.service.VaccineIoOperations", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VaccineIoOperations vaccineIoOperations0 = new VaccineIoOperations();
      // Undeclared exception!
      try { 
        vaccineIoOperations0.newVaccine((Vaccine) null);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // org/isf/vaccine/service/VaccineIoOperationRepository
         //
         verifyException("org.isf.vaccine.service.VaccineIoOperations", e);
      }
  }
}
